name: Ulsan Business Alarm

on:
  schedule:
    - cron: '0 0 * * *' # 매일 아침 9시 (한국 시간)
  workflow_dispatch: # 직접 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 1. 코드를 가져오는 단계

      - name: Set up Python
        uses: actions/setup-python@v5 # 2. 파이썬을 설치하는 단계 (중요!)
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_PW: ${{ secrets.NAVER_PW }}
        run: python ulsan_all.py
