name: Ulsan Business Alarm
 
on:
  schedule:
    - cron: '20 23 * * *'  # 매일 아침 9시 (UTC 0시 = KST 9시)
  workflow_dispatch:      # 수동 실행 버튼
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
 
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
 
      - name: Install libraries
        run: |
          pip install requests beautifulsoup4 lxml selenium
 
      - name: Run script
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_PW: ${{ secrets.NAVER_PW }}
        run: python ulsan_all.py
 
 
