name: Ulsan Business Alarm

on:
  schedule:
    - cron: '0 0 * * *' # 매일 아침 9시 실행
  workflow_dispatch: # 직접 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          pip install requests beautifulsoup4 lxml # lxml 부품 추가

      - name: Run script
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_PW: ${{ secrets.NAVER_PW }}
        run: python ulsan_all.py # 파일 이름이 ulsan_all.py가 맞는지 꼭 확인!
